/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funnyfacelab;

import apcscvm.CVMProgram;
import apcscvm.ViewCanvas;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PrintStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author DSTIGANT
 */
public class FunnyFaceGUI extends javax.swing.JFrame
{
    private FaceView view;
    private ArrayList<Face> model;
    /**
     * Creates new form FunnyFaceGUI
     */
    public FunnyFaceGUI()
    {
        view = new FaceView();
        model = new ArrayList<>();
        initComponents();
        readDataFile();
        
        new CVMProgram( (ViewCanvas)faceCanvas, view, view, model ).start();
    }

    private void writeDataFile()
    {
        try
        {
            PrintStream out = new PrintStream( new File("FunnyFaceData.txt") );
            out.println( groupNameTextField.getText() );
            out.println( classComboBox.getItemCount() );
            for ( int i = 0; i < classComboBox.getItemCount(); i++ )
            {
                out.println( classComboBox.getItemAt( i ) );
            }
            out.println( serverComboBox.getItemCount() + " " + serverComboBox.getSelectedIndex() );
            for ( int i = 0; i < serverComboBox.getItemCount(); i++ )
            {
                out.println( serverComboBox.getItemAt(i) );
            }
        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(FunnyFaceGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void readDataFile()
    {
        try
        {
            Scanner in = new Scanner( new File( "FunnyFaceData.txt" ) );
            groupNameTextField.setText( in.nextLine() );
            classComboBox.removeAllItems();
            int nc = in.nextInt();
            for ( int i = 0; i < nc; i++ )
            {
                classComboBox.addItem( in.next() );
            }
            serverComboBox.removeAllItems();
            int nsip = in.nextInt();
            int ssip = in.nextInt();
            for ( int i = 0; i < nsip; i++ )
            {
                serverComboBox.addItem( in.next() );
            }
            serverComboBox.setSelectedIndex( ssip );
        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(FunnyFaceGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        classComboBox = new javax.swing.JComboBox();
        faceCanvas = new ViewCanvas<FaceView, ArrayList<Face>>( view, model );
        serverComboBox = new javax.swing.JComboBox();
        testFaceButton = new javax.swing.JButton();
        groupNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        classComboBox.setEditable(true);
        classComboBox.setMaximumRowCount(20);
        classComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Face" }));
        classComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                classComboBoxActionPerformed(evt);
            }
        });

        serverComboBox.setEditable(true);
        serverComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "localhost" }));
        serverComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                serverComboBoxActionPerformed(evt);
            }
        });

        testFaceButton.setText("Test Face");
        testFaceButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                testFaceButtonActionPerformed(evt);
            }
        });

        groupNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                groupNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classComboBox, 0, 176, Short.MAX_VALUE)
                    .addComponent(serverComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(testFaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groupNameTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faceCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faceCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testFaceButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_classComboBoxActionPerformed
    {//GEN-HEADEREND:event_classComboBoxActionPerformed
        if ( evt.getActionCommand().equals( "comboBoxChanged" ) )
        {
            String className = (String)classComboBox.getSelectedItem();
            view.setFaceClass( className );
        }
        else if ( evt.getActionCommand().equals( "comboBoxEdited" ) )
        {
            classComboBox.addItem( classComboBox.getSelectedItem() );
            
        }
        
        writeDataFile();
    }//GEN-LAST:event_classComboBoxActionPerformed

    private void serverComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_serverComboBoxActionPerformed
    {//GEN-HEADEREND:event_serverComboBoxActionPerformed
        if ( evt.getActionCommand().equals( "comboBoxEdited" ) )
        {
            serverComboBox.addItem( serverComboBox.getSelectedItem() );
            serverComboBox.setSelectedIndex( serverComboBox.getItemCount() - 1 );
            
        }
        
        writeDataFile();
    }//GEN-LAST:event_serverComboBoxActionPerformed

    private void testFaceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testFaceButtonActionPerformed
    {//GEN-HEADEREND:event_testFaceButtonActionPerformed
        try
        {
            Socket s = new Socket( (String)serverComboBox.getSelectedItem(), 8754 );
            Scanner in = new Scanner( s.getInputStream() );
            ObjectOutputStream oos = new ObjectOutputStream( s.getOutputStream() );
            
            String faceClass = (String)classComboBox.getSelectedItem();
            
            oos.writeObject( groupNameTextField.getText() );
            oos.writeObject( faceClass );
            
            int ulcx = in.nextInt();
            int ulcy = in.nextInt();
            int width = in.nextInt();
            
            Face face = FunnyFaceLab.getNewFace(faceClass, ulcx, ulcy, width);
            if ( face != null )
            {
                BufferedImage bi = new BufferedImage( ulcx + width + 100, ulcy + width + 100, BufferedImage.TYPE_4BYTE_ABGR );
                Graphics g = bi.createGraphics();
                face.paint( g );
                ImageIcon ii = new ImageIcon();
                ii.setImage( bi.getSubimage( ulcx, ulcy, width+1, width+1 ) );
                oos.writeObject( ii );
            }
            
        } catch (IOException ex)
        {
            Logger.getLogger(FunnyFaceGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testFaceButtonActionPerformed

    private void groupNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_groupNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_groupNameTextFieldActionPerformed
        writeDataFile();
    }//GEN-LAST:event_groupNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FunnyFaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FunnyFaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FunnyFaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FunnyFaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FunnyFaceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox classComboBox;
    private java.awt.Canvas faceCanvas;
    private javax.swing.JTextField groupNameTextField;
    private javax.swing.JComboBox serverComboBox;
    private javax.swing.JButton testFaceButton;
    // End of variables declaration//GEN-END:variables
}
